sbatch script/0.sh
sbatch script/1.sh
sbatch script/2.sh
sbatch script/3.sh
sbatch script/4.sh
sbatch script/5.sh
sbatch script/6.sh
sbatch script/7.sh
sbatch script/8.sh
sbatch script/9.sh
sbatch script/10.sh
sbatch script/11.sh
sbatch script/12.sh
sbatch script/13.sh
sbatch script/14.sh
sbatch script/15.sh
sbatch script/16.sh
sbatch script/17.sh
sbatch script/18.sh
sbatch script/19.sh
sbatch script/20.sh
sbatch script/21.sh
sbatch script/22.sh
sbatch script/23.sh
sbatch script/24.sh
sbatch script/25.sh
sbatch script/26.sh
sbatch script/27.sh
sbatch script/28.sh
sbatch script/29.sh
sbatch script/30.sh
sbatch script/31.sh
sbatch script/32.sh
sbatch script/33.sh
sbatch script/34.sh
sbatch script/35.sh
sbatch script/36.sh
sbatch script/37.sh
sbatch script/38.sh
sbatch script/39.sh
sbatch script/40.sh
sbatch script/41.sh
sbatch script/42.sh
sbatch script/43.sh
sbatch script/44.sh
sbatch script/45.sh
sbatch script/46.sh
sbatch script/47.sh
sbatch script/48.sh
sbatch script/49.sh
sbatch script/50.sh
sbatch script/51.sh
sbatch script/52.sh
sbatch script/53.sh
sbatch script/54.sh
sbatch script/55.sh
sbatch script/56.sh
sbatch script/57.sh
sbatch script/58.sh
sbatch script/59.sh
sbatch script/60.sh
sbatch script/61.sh
sbatch script/62.sh
sbatch script/63.sh
sbatch script/64.sh
sbatch script/65.sh
sbatch script/66.sh
sbatch script/67.sh
sbatch script/68.sh
sbatch script/69.sh
sbatch script/70.sh
sbatch script/71.sh
sbatch script/72.sh
sbatch script/73.sh
sbatch script/74.sh
sbatch script/75.sh
sbatch script/76.sh
sbatch script/77.sh
sbatch script/78.sh
sbatch script/79.sh
sbatch script/80.sh
sbatch script/81.sh
sbatch script/82.sh
sbatch script/83.sh
sbatch script/84.sh
sbatch script/85.sh
sbatch script/86.sh
sbatch script/87.sh
sbatch script/88.sh
sbatch script/89.sh
sbatch script/90.sh
sbatch script/91.sh
sbatch script/92.sh
sbatch script/93.sh
sbatch script/94.sh
sbatch script/95.sh
sbatch script/96.sh
sbatch script/97.sh
sbatch script/98.sh
sbatch script/99.sh
